version: '3.3'

services:
  traefik:
    image: traefik:v2.8
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true" 
      - "--api.dashboard=true" 
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ${{ values.name }}-backend:
    image: avaliasystems/${{ values.name }}-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${{ values.name }}-backend.rule=Host(`simple-backend.ch`)"
      - "traefik.http.services.${{ values.name }}-backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.${{ values.name }}-backend.entrypoints=web"

  ${{ values.name }}-frontend:
    image: avaliasystems/${{ values.name }}-frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${{ values.name }}-frontend.rule=Host(`simple-frontend.ch`)"
      - "traefik.http.routers.${{ values.name }}-frontend.entrypoints=web"
